[package]
name = "netease-cloud-music-gtk"
description = "Linux 平台下基于 Rust + GTK 开发的网易云音乐播放器"
version = "0.5.0"
authors = ["gmg137 <gmg137@live.com>"]
license = "GPL-v3"
edition = "2018"
homepage = "https://github.com/gmg137/netease-cloud-music-gtk"

[dependencies]
gtk = "*"
gdk = "*"
gio = "*"
glib = "*"
pango = "*"
reqwest = "*"
gdk-pixbuf ="*"
gstreamer = "*"
gstreamer-player = "*"
cairo-rs = { version = "^0", features = ["png"] }
dbus = "*"

curl = "*"
dirs = "*"
rand = "*"
rustc-serialize = "*"
hex = "*"
num = "*"
aes-soft = "*"
block-modes = "*"
base64 = "*"
openssl = "*"
serde = { version = "*", features = ["derive"] }
serde_json = "*"
regex = "*"
serde_urlencoded = "*"
sled = "*"
lazy_static = "*"
chrono = "*"
rayon = "*"
fragile = "*"
image = "*"

log = "*"
loggerv = "*"
crossbeam-channel = "*"
cargo-rpm = "*"

[features]
default = ["gtk_3_24"]
gtk_3_18 = ["gtk/v3_18", "gio/v2_46"]
gtk_3_22_30 = ["gtk_3_18", "gtk/v3_22_30", "gio/v2_56"]
gtk_3_24 = ["gtk_3_22_30", "gtk/v3_24", "gio/v2_58"]

[dependencies.mpris-player]
version = "0.3.0"
git = "https://gitlab.gnome.org/World/Rust/mpris-player"

[package.metadata.rpm.cargo]
buildflags = ["--release"]

[package.metadata.rpm.targets]
netease-cloud-music-gtk = { path = "/usr/bin/netease-cloud-music-gtk" }

[package.metadata.deb]
depends = "$auto"
section = "sound"
assets = [
    ["target/release/netease-cloud-music-gtk", "usr/bin/", "755"],
    ["netease-cloud-music-gtk.desktop", "usr/share/applications/", "644"],
    ["icons/netease-cloud-music-gtk.svg", "usr/share/pixmaps/", "644"],
]
