[package]
name = "netease-cloud-music-gtk"
description = "Linux 平台下基于 Rust + GTK 开发的网易云音乐播放器"
version = "1.2.1"
authors = ["gmg137 <gmg137@live.com>"]
license = "GPL-v3"
edition = "2018"
homepage = "https://github.com/gmg137/netease-cloud-music-gtk"

[dependencies]
gtk = "^0.9"
gdk = "^0.13"
gio = "^0.9"
glib = "^0.10"
pango = "^0.9"
gdk-pixbuf ="^0.9"
gstreamer = "^0.16"
gstreamer-player = "^0.16"
cairo-rs = { version = "^0.9", features = ["png"] }
mpris-player = "*"

dirs = "*"
rand = "*"
hex = "*"
num = "*"
base64 = "*"
openssl = "*"
serde = { version = "*", features = ["derive"] }
serde_json = "*"
bincode = "*"
regex = "*"
urlqstring = "*"
lazy_static = "*"
chrono = "*"
fragile = "*"
xdg = "*"
futures = "^0.3"
async-std = "^1.6.1"
isahc = { version = "^1.0.1", features = ["cookies"] }
custom_error = "*"

log = "*"
loggerv = "*"

[features]
default = ["gtk_3_24"]
gtk_3_18 = ["gtk/v3_18", "gio/v2_46"]
gtk_3_22_30 = ["gtk_3_18", "gtk/v3_22_30", "gio/v2_56"]
gtk_3_24 = ["gtk_3_22_30", "gtk/v3_24", "gio/v2_58"]

[package.metadata.rpm.cargo]
buildflags = ["--release"]

[package.metadata.rpm.targets]
netease-cloud-music-gtk = { path = "/usr/bin/netease-cloud-music-gtk" }

[package.metadata.deb]
depends = "$auto"
section = "sound"
assets = [
    ["target/release/netease-cloud-music-gtk", "usr/bin/", "755"],
    ["netease-cloud-music-gtk.desktop", "usr/share/applications/", "644"],
    ["icons/netease-cloud-music-gtk.svg", "usr/share/pixmaps/", "644"],
]
